# Titanic Data Analysis

## Import Libraries

In [22]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## Data Extraction

In [23]:
from sklearn.datasets import fetch_openml
titanic = fetch_openml("titanic", version=1, as_frame=True).frame #dataframe

In [24]:
titanic.head()
titanic.info()
titanic.describe()

<class 'pandas.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   pclass     1309 non-null   int64
 1   survived   1309 non-null   category
 2   name       1309 non-null   str
 3   sex        1309 non-null   category
 4   age        1046 non-null   float64
 5   sibsp      1309 non-null   int64
 6   parch      1309 non-null   int64
 7   ticket     1309 non-null   str
 8   fare       1308 non-null   float64
 9   cabin      295 non-null    str
 10  embarked   1307 non-null   category
 11  boat       486 non-null    str
 12  body       121 non-null    float64
 13  home.dest  745 non-null    str
dtypes: category(3), float64(3), int64(3), str(5)
memory usage: 116.6 KB

,pclass,age,sibsp,parch,fare,body
count,1309.000000,1046.000000,1309.000000,1309.000000,1308.000000,121.000000
mean,2.294882,29.881135,0.498854,0.385027,33.295479,160.809917
std,0.837836,14.413500,1.041658,0.865560,51.758668,97.696922
min,1.000000,0.166700,0.000000,0.000000,0.000000,1.000000
25%,2.000000,21.000000,0.000000,0.000000,7.895800,72.000000
50%,3.000000,28.000000,0.000000,0.000000,14.454200,155.000000
75%,3.000000,39.000000,1.000000,0.000000,31.275000,256.000000
max,3.000000,80.000000,8.000000,9.000000,512.329200,328.000000

## Data Cleaning

### Missing Values

In [25]:

titanic.drop(columns=["cabin", "boat", "body", "home.dest"], inplace=True) #too much null
titanic["fare"] = titanic["fare"].fillna(titanic["fare"].median()) #numeric
titanic["embarked"] = titanic["embarked"].fillna(titanic["embarked"].mode()[0]) #categorical
titanic["age"] = titanic["age"].fillna(titanic["age"].median()) #numeric

In [26]:
titanic.isna().sum()

pclass      0
survived    0
name        0
sex         0
age         0
sibsp       0
parch       0
ticket      0
fare        0
embarked    0
dtype: int64

### Wrong Format

In [27]:
titanic.dtypes

pclass         int64
survived    category
name             str
sex         category
age          float64
sibsp          int64
parch          int64
ticket           str
fare         float64
embarked    category
dtype: object

In [28]:
titanic["age"] = titanic["age"].astype(int)
titanic["survived"] = titanic["survived"].astype(bool)
titanic.dtypes

pclass         int64
survived        bool
name             str
sex         category
age            int64
sibsp          int64
parch          int64
ticket           str
fare         float64
embarked    category
dtype: object

### Out of Range

In [29]:
titanic.describe()

            pclass          age        sibsp        parch         fare
count  1309.000000  1309.000000  1309.000000  1309.000000  1309.000000
mean      2.294882    29.484339     0.498854     0.385027    33.281086
std       0.837836    12.916721     1.041658     0.865560    51.741500
min       1.000000     0.000000     0.000000     0.000000     0.000000
25%       2.000000    22.000000     0.000000     0.000000     7.895800
50%       3.000000    28.000000     0.000000     0.000000    14.454200
75%       3.000000    35.000000     1.000000     0.000000    31.275000
max       3.000000    80.000000     8.000000     9.000000   512.329200

In [30]:
titanic[titanic["age"] > 100]
print(titanic["sibsp"].value_counts())
print(titanic["parch"].value_counts())

sibsp
0    891
1    319
2     42
4     22
3     20
8      9
5      6
Name: count, dtype: int64
parch
0    1002
1     170
2     113
3       8
4       6
5       6
6       2
9       2
Name: count, dtype: int64

In [31]:
titanic[titanic["parch"] == 9]

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,embarked
1179,3,True,"Sage, Mr. John George",male,28,1,9,CA. 2343,69.55,S
1180,3,True,"Sage, Mrs. John (Annie Bullen)",female,28,1,9,CA. 2343,69.55,S

In [32]:
titanic.duplicated().sum()

np.int64(0)